### ISSUE TITLE
AKS kubelet issue

### ISSUE THREAD

**Issue by jkdey** [newrelic/nri-discovery-kubernetes#7]
ran into an issue where kubelet API was not returning data in AKS 1.15.7

> failed to connect to Kubernetes: failed to unmarshall result in to list of pods: invalid character 'U' looking for beginning of value

changing integration configmap to the following fixed this

```
  consul-config.yml: |
    ---
    # Run auto discovery to find pods with label "app=consul"
    # https://docs.newrelic.com/docs/integrations/host-integrations/installation/container-auto-discovery
    discovery:
      command:
        # Run NRI Discovery for Kubernetes
        # https://github.com/newrelic/nri-discovery-kubernetes
        exec: /var/db/newrelic-infra/nri-discovery-kubernetes --port=10255 --insecure
        match:
          label.app: consul
    integrations:
      - name: nri-consul
        env:
          # Use the discovered IP as the host address
          HOSTNAME: ${discovery.ip}
```
